workspace:
  base: /drone
  path: src

pipeline:
  restore:
    image: jmccann/drone-s3-cache
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    pull: true
    restore: true

  dryrun:
    image: plugins/docker
    repo: owncloudci/php
    storage_path: /drone/src/docker
    pull_image: true
    dry_run: true
    tags: [ '7.0' ]
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/php
    storage_path: /drone/src/docker
    pull_image: true
    tags: [ '7.0' ]
    when:
      event: [ push ]
      branch: [ '7.0' ]

  microbadger:
    image: zyclonite/drone-webhook
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      event: [ push ]
      branch: [ '7.0' ]

  rebuild:
    image: jmccann/drone-s3-cache
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    rebuild: true
    mount:
      - docker

  flush:
    image: jmccann/drone-s3-cache
    secrets: [ cache_s3_server, cache_s3_access_key, cache_s3_secret_key ]
    flush: true
    flush_age: 14

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    channel: marketplace
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]
