workspace:
  base: /drone
  path: src

pipeline:
  dryrun:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/php
    dry_run: true
    tags: [ '7.0' ]
    when:
      event: [ pull_request ]

  docker:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: owncloudci/php
    tags: [ '7.0' ]
    when:
      branch: [ '7.0' ]

  microbadger:
    image: zyclonite/drone-webhook
    pull: true
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      branch: [ '7.0' ]

  slack:
    image: plugins/slack
    pull: true
    secrets: [ slack_webhook ]
    channel: drone
    when:
      status: [ success, failure ]
